import React from 'react';

const PolicySection: React.FC<{ title: string; children: React.ReactNode; }> = ({ title, children }) => (
    <div className="space-y-3">
        <h2 className="text-xl font-bold text-light-heading dark:text-dark-heading border-b border-light-border dark:border-dark-border pb-2">{title}</h2>
        <div className="space-y-2 text-light-text dark:text-dark-text">
            {children}
        </div>
    </div>
);

const TermsOfServicePage: React.FC = () => {
    return (
        <div className="flex-1 flex flex-col max-w-4xl mx-auto w-full p-4 sm:p-6 lg:p-8 space-y-8 animate-fade-in">
            <header className="text-left">
                 <h1 className="text-3xl sm:text-4xl font-extrabold text-light-heading dark:text-dark-heading">Terms of Service</h1>
                 <p className="text-light-text dark:text-dark-text mt-2">Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
            </header>
            
            <main className="space-y-8">
                <PolicySection title="1. Acceptance of Terms">
                    <p>By accessing or using RoleReady AI (the "Service"), you agree to be bound by these Terms of Service ("Terms"). If you disagree with any part of the terms, then you may not access the Service. Your agreement is confirmed by checking the "I have read and agree to the Terms of Service" box before using the analysis feature.</p>
                </PolicySection>

                <PolicySection title="2. Description of Service">
                    <p>RoleReady AI is an application that uses third-party Artificial Intelligence (Google's Gemini API) to analyze user-provided text from a resume and a job description. The Service provides an automated analysis, scores, and suggestions intended to be used as a guide for improving a resume. The Service is for informational purposes only.</p>
                </PolicySection>

                <PolicySection title="3. AI-Generated Content and Disclaimer of Warranties">
                    <p>You acknowledge and agree that:</p>
                    <ul className="list-disc list-inside space-y-2 pl-4">
                        <li>All analysis, scores, suggestions, and rewritten content are generated by an AI and are not reviewed by a human. This content may contain errors, inaccuracies, or biases.</li>
                        <li>The Service is provided on an "AS IS" and "AS AVAILABLE" basis. We make no warranty that the Service will meet your requirements, be uninterrupted, timely, secure, or error-free.</li>
                        <li><strong>RoleReady AI does not guarantee any outcome, including but not limited to, securing an interview, job offer, or any form of employment.</strong> The tool is for informational and educational purposes only. You are solely responsible for the final content of your resume and your career decisions.</li>
                    </ul>
                </PolicySection>

                <PolicySection title="4. Limitation of Liability">
                    <p>To the fullest extent permitted by applicable law, in no event shall RoleReady AI, its affiliates, or its developers be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses, resulting from (a) your access to or use of or inability to access or use the Service; (b) any conduct or content of any third party on the Service; or (c) unauthorized access, use, or alteration of your transmissions or content.</p>
                </PolicySection>

                <PolicySection title="5. Acceptable Use">
                    <p>You agree not to use the Service for any unlawful purpose or to engage in any of the following prohibited activities:</p>
                    <ul className="list-disc list-inside space-y-2 pl-4">
                        <li>Submitting any content that is illegal, harmful, threatening, abusive, defamatory, or otherwise objectionable.</li>
                        <li>Attempting to interfere with, compromise the system integrity or security of, or decipher any transmissions to or from the servers running the Service.</li>
                        <li>Using any automated system, including without limitation "robots," "spiders," or "offline readers," to access the Service in a manner that sends more request messages to the servers than a human can reasonably produce in the same period by using a conventional on-line web browser.</li>
                    </ul>
                </PolicySection>

                <PolicySection title="6. Intellectual Property">
                    <p>We retain all right, title, and interest in and to the Service, including all related intellectual property rights. You retain all rights to the resume and job description content you provide to the Service. You grant us a temporary, non-exclusive, royalty-free license to use your content solely for the purpose of providing the Service to you during your session.</p>
                </PolicySection>
                
                <PolicySection title="7. Changes to Terms">
                     <p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide notice of changes by updating the "Last updated" date of these Terms. By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms.</p>
                </PolicySection>
            </main>

            <footer className="text-center py-6 border-t border-light-border dark:border-dark-border">
                <p className="text-light-subtle dark:text-dark-subtle">&copy; {new Date().getFullYear()} RoleReady AI. All rights reserved.</p>
            </footer>
        </div>
    );
};

export default TermsOfServicePage;